set2/recipies/urls.py
from django.urls import path
from . import views

app_name = 'recipie'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('radmin/',views.AdminRecipies, name='radmin'),
    path('add/',views.addrecipies),
    path('user/',views.ViewRecipies, name='user'),

]

set2/set2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('recipies.urls'))
]

set2/recipies/models.py
from django.db import models

# Create your models here.
class ItemList(models.Model):
    recipie = models.TextField() 
    comment = models.TextField()

set2/recipies/views.py
from django.shortcuts import render
from .models import ItemList
from django.http import HttpResponseRedirect 

# Create your views here.
def index(request):
    return render (request, 'index.html')


def ViewRecipies(request):
    items = ItemList.objects.all()
    return render(request, 'List.html',  {'all_items':items})

def AdminRecipies(request):
    items = ItemList.objects.all()
    return render(request, 'Add.html', {'all_items':items})

def addrecipies(request):
    new_item = ItemList()
    new_item.recipie = request.POST.get('recipie')
    new_item.save()
    return HttpResponseRedirect('/radmin/') 

set2/recipies/templates/Add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Recipies</title>
</head>
<body style="background-color: #eed6d3;">
    
<div class="container">
    
    <div class="row" style="margin-top: 20px;">
        <div class="col">

            <div class="row">
                <form class="form-inline" action="/add/" method = "post">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-8">
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="recipie" class="sr-only"></label>
                                <input type="text" class="form-control" name="recipie" >
                              </div>
                        </div>
                        <div class="col-4" style="margin-top: 25px;">
                            <button type="submit" class="btn btn-primary mb-2" style="background-color: #a49393; border-color: #a49393;">Add Recipie</button>
                            
                        </div>
                    </div>
                    
                  </form>
            </div>

            {% for i in all_items %} 
            <div class="row">
                <div class="col-1"></div>
                <div class="col-6">
                    <div class="card  text-white bg-dark mb-3" style="color: #67595e; border-color: #e8b4b8;">
                        <div class="card-body" style="background-color: #e8b4b8; color: #67595e; border-color: #e8b4b8;">
                            {{i.recipie}}
                        </div>
                      </div>
                </div>
                <div class="col-3"></div>
            </div>
            {% endfor %}
            <p><a href="{% url 'recipie:index' %}" class="btn btn-primary" style="background-color: #67595e; border-color: #67595e; color: #eed6d3;">Exit</a></p>
        </div>
    </div>
            

</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

set2/recipies/templates/List.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Recipies</title>
</head>
<body style="background-color: #eed6d3;">
    
<div class="container" style="background-color: #eed6d3;">
{% for i in all_items %} 
            <div class="row">
                <div class="col-1"></div>
                <div class="col-6">
                    <div class="card  text-white bg-dark mb-3" style="border-color: #e8b4b8;">
                        <div class="card-body" style="background-color: #e8b4b8; color: #67595e; border-color: #e8b4b8;">
                            {{i.recipie}}
                        </div>
                      </div>
                </div>
                <div class="col-3"></div>
            </div>
            {% endfor %}
            <p><a href="{% url 'recipie:index' %}" class="btn btn-primary" style="background-color: #67595e; border-color: #67595e; color: #eed6d3;">Exit</a></p>
        </div>
    </div>
  
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

set2/recipies/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Recipies for you</title>
</head>
<body>
                                    
<div class="container" style="width: 700px; display: block;">
    <div class="card text-center" style="margin-top: 200px;background-color: #eed6d3; width: 700px; ">
          <h5 class="card-title" style="color: #67595e;">Find recipies you like here!</h5>
          <h3 style="font-size: small;">Developed  by Ria Ann Bijo 22112033</h3>
          <a href="{% url 'recipie:radmin' %}" class="btn btn-primary" style="background-color: #e8b4b8; border-color: #e8b4b8; color: #67595e;">Admin</a>

          <a href="{% url 'recipie:user' %}" class="btn btn-primary" style="margin-top: 10px;background-color: #e8b4b8; border-color: #e8b4b8; color: #67595e;">Find Recipies</a>
          
       
        
      </div>
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>